package day2;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class UtilsGame {

    public static String getData() {
        return "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "C X";
    }

    public static List<String> getList(String data, Boolean isPlayerOne) {
        int position = isPlayerOne ? 0 : 1;
        List<String> result = new ArrayList<>();
        List<String> list = List.of(data.split("\\R"));
        for (String value : list) {
            String s = value.split(" ")[position];
            result.add(s);
        }
        return result;
    }
}
